### ISSUE TITLE
Permission to publish article from Tech Blog site

### ISSUE THREAD

**Issue by Content-Technology** [Netflix-Skunkworks/UnrealValidationFramework#1]
Hi guys, I wanted to see if we could get permission to run your Netflix Technology Blog article, Virtual Production — A Validation Framework For Unreal Engine, in our next issue of Content+Technology magazine (https://www.content-technology.com https://issuu.com/contentandtechnology )
Our publication, launched 20 years ago, goes out to media technology types in Australia, New Zealand and Southeast Asia.
We previously published Remote Workstations for the Discerning Artist by Michelle Brenner, Senior Software Engineer, Studio Infrastructure - https://issuu.com/contentandtechnology/docs/content_technology_asia_april-may_2021/23
Naturally, authors would be credited and the article would be linked, as is the case with the blog article, to this GitHub page.
Please let me know if this is possible, or who to contact for corporate clearance, if needed.
Thanks and regards
Phil Sandberg
Publisher
Content+Technology

**Comment by davisadam10** [comment]
No problems with this, sorry for the delay
