### ISSUE TITLE
Plugin Content not valid when "Download ZIP"

### ISSUE THREAD

**Issue by ahrenm** [Netflix-Skunkworks/UnrealValidationFramework#2]
Not a huge issue, but it looks like the contents of the plugins Content directory is not getting populated correctly if the project is downloaded from Github as a ZIP. I think it just pulls the Github LFS pointers. The resulting UASSET files are not valid for UE. Doing a Get from a Github client seems to behave as expected.

Noted here in case anyone gets tripped up by it.

**Comment by davisadam10** [comment]
Thank you for pointing this out, whilst typically we look to people to clone repos, or download official releases there is no reason why this should work.

The feature has been enabled on github so any future downloads as ZIP also include the git lfs UASSETs.
